runtime: python39

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

entrypoint: uvicorn api:app --host 0.0.0.0 --port $PORT

instance_class: F4_1G # Change to a larger instance class like F2 or F4

health_check:
  enable_health_check: true
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60
