runtime: python39

handlers:
- url: /static
  static_dir: frontend-trackerfitness/build/static

- url: /api/.*
  script: auto

- url: /.*
  static_files: frontend-trackerfitness/build/index.html
  upload: frontend-trackerfitness/build/index.html

# entrypoint: gunicorn -w 2 -k uvicorn.workers.UvicornWorker api:app --bind :$PORT

entrypoint: uvicorn api.api:app --host 0.0.0.0 --port $PORT

instance_class: F4_1G

health_check:
  enable_health_check: true
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60
